### ISSUE TITLE
Значение %login% не принимается, если содержит символ(ы)

### ISSUE THREAD

**Issue by BADtochka** [microwin7/GravitLauncher-TextureProvider#1]
### `BAD.`:

> Файл текстуры (в сети доступен)
>  ![image](https://user-images.githubusercontent.com/75701093/128411398-a09aa97f-af8e-4afd-a05c-9c6e681de54d.png)
> 
> Ответ в браузере по логину
> ...TextureProvider.php?login=BAD.
> `{}`

### `BAD`:

> Файл текстуры
> ![image](https://user-images.githubusercontent.com/75701093/128412017-490a8e0a-dcc2-45ac-838a-3a909b1b836d.png)
> 
> Ответ в браузере по логину
> ...TextureProvider.php?login=BAD
> ```
> {
>     "skin": {
>         "url": "https://.../play/TextureProvider.php?login=BAD&type=skin",
>         "digest": "ZTgwOTExZmJhZjI5NWYxYjFhNTE5OGY1ZjhlODYyMTc="
>     },
>     "cloak": {
>         "url": "https://.../play/TextureProvider.php?login=BAD&type=cloak",
>         "digest": "NTcyYWQ5MDM0ZmU3MmU0NmVkY2Y1ZDBkNTBlODgzOWE="
>     }
> }
> ```

**Comment by microwin7** [comment]
Здравствуйте, не могу предложить хорошего решения данного вопроса
Так как такие данные не стандартизированы и могут иметь уязвимость доступа к каталогам выше, через прямой запрос
На свой страх и риск можно убрать проверку, но тогда защиту от несанкционированного доступа я не могу гарантировать
// regex_valid($login) ?: response();
Так же могу попробовать написать функцию которая сможет дополнительно хотя бы проверять, что логин не начинается на `.`
Как индивидуальный случай, поверх regex проверки

**Comment by BADtochka** [comment]
Спасибо, закоментил строчку с проверкой ника, защита мне не нужна толком, некоммерческий проект.
